name: Docker Image CI

on:
  workflow_call:
    inputs:
      DB_TYPE_TO_BUILD:
        required: true
        type: string

jobs:

  dockerhub:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Load environment variables
        uses: ilaipi-freedom/load-env-action@latest
        with:
          env_content: ${{ secrets.ENV }}

      - name: Extract DockerHub metadata
        id: meta_hub
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.DB_TYPE_TO_BUILD }}-helper
          tags: |
            # 如果是 main 分支提交，使用当前时间和 latest 标签
            type=raw,value=latest
            type=raw,value={{date 'YYYYMMDD-HHmm' tz='+08:00'}}
            # 如果是 tag 提交，使用默认标签策略
            type=ref,event=tag

      - name: Extract HuaweiCloud metadata
        id: meta_huaweicloud
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_HUB_SPACE }}/${{ inputs.DB_TYPE_TO_BUILD }}-helper
          tags: |
            # 如果是 main 分支提交，使用当前时间和 latest 标签
            type=raw,value=latest
            type=raw,value={{date 'YYYYMMDD-HHmm' tz='+08:00'}}
            # 如果是 tag 提交，使用默认标签策略
            type=ref,event=tag

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.DB_TYPE_TO_BUILD }}
          push: true
          tags: ${{ steps.meta_hub.outputs.tags }}

      - name: Login to Huawei Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build and push to Huawei Cloud
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.DB_TYPE_TO_BUILD }}
          push: true
          tags: ${{ steps.meta_huaweicloud.outputs.tags }}
