name: Docker Image CI

on:
  workflow_call:
    inputs:
      DB_TYPE_TO_BUILD:
        required: true
        type: string
    secrets:
      DOCKER_HUB_TOKEN:
        required: true
      DOCKER_HUB_USERNAME:
        required: true

jobs:

  dockerhub:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: define-tag
      id: define-image-tag
      run:
        echo "IMAGE_TAG_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.DB_TYPE_TO_BUILD }}-helper:$(date +%s)" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./${{ inputs.DB_TYPE_TO_BUILD }}
        push: true
        tags: ${{ steps.define-image-tag.outputs.IMAGE_TAG_NAME}},${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.DB_TYPE_TO_BUILD }}-helper:latest
